.TH BILREMINDER 1 "Jan 16, 2007

.SH NAME
billreminder \- Never forget to pay a bill again!

.SH SYNOPSIS
.B billreminder [OPTIONS]

.SH DESCRIPTION
BillReminder is a small and quick accounting application
designed to allow for easy tracking of bills.

.SH OPTIONS
BillReminder accept the following command-line call methods:
.TP
.B \-h, \-?, --help
Show a short usage summary.
.TP
.B --about
Show about dialog.
.TP
.B --add
Adds a new record to the database.
.TP
.B --standalone
Access database directly, without daemon.
.TP
.B \-v, --version
Show the program version.

.SH AUTHORS
Written by Og Maciel <ogmaciel@gnome.org> and
Luiz Armesto <luiz.armesto@gmail.com>
with some contributors that can be found on the project page.

.SH HOMEPAGE
http://code.google.com/p/billreminder/

.SH COPYRIGHT
Copyright \(co 2006, 2008 Og Maciel

.SH "SEE ALSO"
.BR billreminderd (1)
