#!/usr/bin/python
# Copyright (C) 2007 by Og Maciel <og.maciel@gmail.com>
#
# Provided under MIT licence, please see included
# COPYRIGHT and/or COPYING file.

import os
import sys

try:
 	import pygtk
  	pygtk.require("2.0")
except:
  	pass
try:
	import gtk
	import gtk.glade
except:
    print >>sys.stderr, _('You need to install python-glade2 and/or pygtk2 (gtk2) or set your PYTHONPATH correctly.\ntry: export PYTHONPATH=/usr/local/lib/python2.4/site-packages/')
    sys.exit(1)

from billreminder import BillReminder

app = BillReminder()
gtk.main()
